production:
  production:
  adapter: postgresql
  encoding: unicode
  database: railway
  username: postgres
  password: eGKlKYjYyLQZKfUcBrhSwCQOINFiGijO
  host: gondola.proxy.rlwy.net
  port: 55382
  pool: 5
