production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
  queue:
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
